### ISSUE TITLE
2장 captions_train-val2014.zip 주소

### ISSUE THREAD

**Issue by ychoi-kr** [wikibook/mpytc#3]
2장의 다운로드 부분에..

http://msvocds.blob.core.windows.net/annotations-1-0-3/captions_train-val2014.zip 주소가 안되네요...

![제목 없음](https://github.com/wikibook/mpytc/assets/93734094/2921e447-689d-46db-b8d5-9f1b17f2ac1f)

_Originally posted by @kakaon1 in https://github.com/wikibook/mpytc/issues/1#issuecomment-1631759652_

**Comment by ychoi-kr** [comment]
http://msvocds.blob.core.windows.net/annotations-1-0-3/captions_train-val2014.zip 에 접근이 안 되네요. 아래 주소로 바꿔서 시도해 보시기 바랍니다.

http://images.cocodataset.org/annotations/annotations_trainval2014.zip

**Comment by kakaon1** [comment]
잘 됩니다 고맙습니다!
